import * as fs from "fs";
import * as path from "path";

const schemaPath = path.resolve(__dirname, "../prisma/schema.prisma");
const schema = fs.readFileSync(schemaPath, "utf8");

const tenantFilePath = path.resolve(__dirname, "../../../apps/web/src/lib/prisma-tenant.ts");
let tenantFile = fs.readFileSync(tenantFilePath, "utf8");

const modelRegex = /model\s+(\w+)\s*\{[^}]*?tenantId\s+String/gs;
const modelsFromSchema: string[] = [];
let match;
while ((match = modelRegex.exec(schema)) !== null) {
    if (!modelsFromSchema.includes(match[1])) {
        modelsFromSchema.push(match[1]);
    }
}

const formattedArray = `// --- AUTOGENERATED FALLBACK START ---\n        isolatedModels = [\n            ${modelsFromSchema.map(m => `'${m}'`).join(',\n            ')}\n        ];\n        // --- AUTOGENERATED FALLBACK END ---`;

const newTenantContent = tenantFile.replace(/\/\/\s*---\s*AUTOGENERATED FALLBACK START\s*---[\s\S]*?\/\/\s*---\s*AUTOGENERATED FALLBACK END\s*---/, formattedArray);

fs.writeFileSync(tenantFilePath, newTenantContent);
console.log(`✅ Injetado fallback estático DMMF com ${modelsFromSchema.length} models com tenantId em prisma-tenant.ts.`);
