import * as fs from "fs";
import * as path from "path";

const schemaPath = path.resolve(__dirname, "../prisma/schema.prisma");
const schema = fs.readFileSync(schemaPath, "utf8");

const tenantFilePath = path.resolve(__dirname, "../../../apps/web/src/lib/prisma-tenant.ts");
let tenantFile = fs.readFileSync(tenantFilePath, "utf8");

const isolatedModels: string[] = [];
const globalModels: string[] = [];

let currentModel: string | null = null;
let hasTenantId = false;

for (const line of schema.split('\n')) {
    const trimmed = line.trim();

    if (trimmed.startsWith('model ') && trimmed.endsWith('{')) {
        currentModel = trimmed.split(/\s+/)[1];
        hasTenantId = false;
        continue;
    }

    if (currentModel) {
        // Simple check: if a line defines "tenantId String"
        if (trimmed.startsWith('tenantId') && trimmed.includes('String')) {
            hasTenantId = true;
        }

        if (trimmed === '}') {
            if (hasTenantId) {
                isolatedModels.push(currentModel);
            } else {
                globalModels.push(currentModel);
            }
            currentModel = null;
        }
    }
}

const formattedArray = `// --- AUTOGENERATED FALLBACK START ---
    const staticIsolatedModels = [
        ${isolatedModels.map((m) => `'${m}'`).join(',\n        ')}
    ];

    const staticGlobalModels = [
        ${globalModels.map((m) => `'${m}'`).join(',\n        ')}
    ];
    // --- AUTOGENERATED FALLBACK END ---`;

const newTenantContent = tenantFile.replace(/\/\/\s*---\s*AUTOGENERATED FALLBACK START\s*---[\s\S]*?\/\/\s*---\s*AUTOGENERATED FALLBACK END\s*---/, formattedArray);

fs.writeFileSync(tenantFilePath, newTenantContent);
console.log(`✅ [DMMF Fallback] Injetado com sucesso no PRISMA-TENANT.TS`);
console.log(`   - Modelos Isolados (Tenant): ${isolatedModels.length}`);
console.log(`   - Modelos Globais: ${globalModels.length}`);
