import { Prisma } from '@prisma/client';

export function tenantExtension(tenantId: string | null) {
    let isolatedModels: string[] = [];
    if (Prisma.dmmf?.datamodel?.models) {
        isolatedModels = Prisma.dmmf.datamodel.models
            .filter((m) => m.fields.some((f) => f.name === 'tenantId'))
            .map((m) => m.name);
    } else {
        console.warn("[SECURITY_WARN] Prisma DMMF indisponível em runtime (comum no Vercel Edge/Serverless). Usando fallback estático de isolamento.");
        // --- AUTOGENERATED FALLBACK START ---
        isolatedModels = [
            'User',
            'Customer',
            'Vehicle',
            'Service',
            'Product',
            'ServiceProductTemplate',
            'StockMovement',
            'ServiceOrder',
            'OrderItem',
            'OrderItemCommission',
            'CommissionSettlement',
            'OrderProduct',
            'InspectionItem',
            'InspectionDamage',
            'Payment',
            'NotificationLog',
            'AuditLog',
            'MessageTemplate',
            'Subscription',
            'PartnerCommission',
            'TenantSequence',
            'PendingRestock'
        ];
        // --- AUTOGENERATED FALLBACK END ---
    }

    const injectTenantIntoConnects = (data: any, currentModelName: string): any => {
        if (!data || typeof data !== 'object') return data;

        const modelDef = Prisma.dmmf.datamodel.models.find(m => m.name === currentModelName);
        if (!modelDef) return data;

        const newData = { ...data };

        // 🛡️ SECURITY: Deep Freeze - Impede que campos de tenantId aninhados vazem outro Tenant.
        const isCurrentIsolated = isolatedModels.includes(currentModelName);
        if (isCurrentIsolated && tenantId) {
            if ('tenantId' in newData) {
                newData.tenantId = tenantId;
            }
        }

        for (const [key, value] of Object.entries(newData)) {
            if (value && typeof value === 'object' && !Array.isArray(value)) {
                const fieldDef = modelDef.fields.find(f => f.name === key);

                if (fieldDef && fieldDef.kind === 'object') {
                    const targetModelName = fieldDef.type;
                    const targetIsIsolated = isolatedModels.includes(targetModelName);
                    const operationObj = value as any;

                    if (targetIsIsolated) {
                        if (operationObj.connect) {
                            if (Array.isArray(operationObj.connect)) {
                                operationObj.connect = operationObj.connect.map((c: any) => ({ ...c, tenantId }));
                            } else {
                                operationObj.connect = { ...operationObj.connect, tenantId };
                            }
                        }

                        if (operationObj.connectOrCreate) {
                            if (Array.isArray(operationObj.connectOrCreate)) {
                                operationObj.connectOrCreate = operationObj.connectOrCreate.map((c: any) => ({
                                    where: { ...c.where, tenantId },
                                    create: { ...injectTenantIntoConnects(c.create, targetModelName), tenantId }
                                }));
                            } else {
                                operationObj.connectOrCreate = {
                                    where: { ...operationObj.connectOrCreate.where, tenantId },
                                    create: { ...injectTenantIntoConnects(operationObj.connectOrCreate.create, targetModelName), tenantId }
                                };
                            }
                        }

                        if (operationObj.create) {
                            if (Array.isArray(operationObj.create)) {
                                operationObj.create = operationObj.create.map((c: any) => ({
                                    ...injectTenantIntoConnects(c, targetModelName),
                                    tenantId
                                }));
                            } else {
                                operationObj.create = {
                                    ...injectTenantIntoConnects(operationObj.create, targetModelName),
                                    tenantId
                                };
                            }
                        }

                        if (operationObj.update) {
                            if (Array.isArray(operationObj.update)) {
                                operationObj.update = operationObj.update.map((u: any) => ({
                                    ...u,
                                    data: injectTenantIntoConnects(u.data || u, targetModelName)
                                }));
                            } else if (operationObj.update.data) {
                                operationObj.update.data = injectTenantIntoConnects(operationObj.update.data, targetModelName);
                            } else {
                                operationObj.update = injectTenantIntoConnects(operationObj.update, targetModelName);
                            }
                        }

                        if (operationObj.upsert) {
                            if (Array.isArray(operationObj.upsert)) {
                                operationObj.upsert = operationObj.upsert.map((u: any) => ({
                                    ...u,
                                    where: { ...u.where, tenantId },
                                    create: { ...injectTenantIntoConnects(u.create, targetModelName), tenantId },
                                    update: injectTenantIntoConnects(u.update || u, targetModelName)
                                }));
                            } else {
                                operationObj.upsert = {
                                    ...operationObj.upsert,
                                    where: { ...operationObj.upsert.where, tenantId },
                                    create: { ...injectTenantIntoConnects(operationObj.upsert.create, targetModelName), tenantId },
                                    update: injectTenantIntoConnects(operationObj.upsert.update || operationObj.upsert, targetModelName)
                                };
                            }
                        }
                    }
                }
            }
        }
        return newData;
    };

    return Prisma.defineExtension((client) => {
        return client.$extends({
            query: {
                $allModels: {
                    async $allOperations({ model, operation, args, query }) {
                        if (!isolatedModels.includes(model)) {
                            return query(args);
                        }

                        if (!tenantId) {
                            // Operando sem tenant no contexto (ex: public procedure, webhook)
                            // Aplica política MISS-CLOSED: impede queries em models isolados que não tenham tenantId explícito.
                            const checkHasTenantExplicitly = (obj: any): boolean => {
                                if (!obj || typeof obj !== 'object') return false;
                                if ('tenantId' in obj && obj.tenantId !== undefined && obj.tenantId !== null) return true;
                                if (Array.isArray(obj.AND) && obj.AND.some(checkHasTenantExplicitly)) return true;
                                if (Array.isArray(obj.OR) && obj.OR.some(checkHasTenantExplicitly)) return true;
                                return false;
                            };

                            const isRead = ['findFirst', 'findUnique', 'findMany', 'count', 'aggregate', 'groupBy'].includes(operation);
                            const isWrite = ['create', 'createMany', 'update', 'updateMany', 'delete', 'deleteMany', 'upsert'].includes(operation);
                            const anyArgs = args as any;

                            if (isRead && (!anyArgs?.where || !checkHasTenantExplicitly(anyArgs.where))) {
                                throw new Error(`[SECURITY_FATAL] Tentativa de leitura global no model isolado '${model}' bloqueada. É obrigatório passar 'tenantId' no 'where' para rotas públicas.`);
                            }

                            if (isWrite) {
                                if (operation === 'create' || operation === 'createMany') {
                                    const dataArr = Array.isArray(anyArgs?.data) ? anyArgs.data : [anyArgs?.data];
                                    const hasTenantInAll = dataArr.every((d: any) => d && 'tenantId' in d && d.tenantId !== undefined && d.tenantId !== null);
                                    if (!hasTenantInAll) throw new Error(`[SECURITY_FATAL] Tentativa de criação no model '${model}' sem 'tenantId' explícito no 'data' bloqueada.`);
                                } else if (['update', 'updateMany', 'delete', 'deleteMany'].includes(operation)) {
                                    if (!anyArgs?.where || !checkHasTenantExplicitly(anyArgs.where)) {
                                        throw new Error(`[SECURITY_FATAL] Tentativa de mutação global no model '${model}' bloqueada. Passe 'tenantId' explícito no 'where'.`);
                                    }
                                } else if (operation === 'upsert') {
                                    if (!anyArgs?.where || !checkHasTenantExplicitly(anyArgs.where) || !anyArgs?.create || !('tenantId' in anyArgs.create && anyArgs.create.tenantId !== undefined && anyArgs.create.tenantId !== null)) {
                                        throw new Error(`[SECURITY_FATAL] Upsert bloqueado no model '${model}'. 'tenantId' deve estar explícito no 'where' e no 'create'.`);
                                    }
                                }
                            }

                            return query(args);
                        }

                        // For tenant-specific models, inject tenantId filter
                        if (['findFirst', 'findUnique', 'findMany', 'count', 'aggregate', 'groupBy', 'update', 'updateMany', 'delete', 'deleteMany', 'upsert'].includes(operation)) {
                            const newArgs = { ...args } as any;
                            newArgs.where = {
                                ...newArgs.where,
                                tenantId: tenantId,
                            };

                            if (operation === 'upsert') {
                                if (newArgs.create) {
                                    newArgs.create = {
                                        ...injectTenantIntoConnects(newArgs.create, model),
                                        tenantId: tenantId
                                    };
                                }
                                if (newArgs.update) {
                                    newArgs.update = injectTenantIntoConnects(newArgs.update, model);
                                }
                            }

                            args = newArgs;
                        }

                        // For creation, ensure tenantId is injected and deep connects are verified
                        if (operation === 'create' || operation === 'createMany' || operation === 'update') {
                            const newArgs = { ...args } as any;

                            if (newArgs.data) {
                                if (Array.isArray(newArgs.data)) {
                                    newArgs.data = newArgs.data.map((item: any) => ({
                                        ...injectTenantIntoConnects(item, model),
                                        tenantId: tenantId,
                                    }));
                                } else {
                                    newArgs.data = {
                                        ...injectTenantIntoConnects(newArgs.data, model),
                                        ...(operation !== 'update' ? { tenantId: tenantId } : {})
                                    };
                                }
                            }

                            return query(newArgs);
                        }

                        // Allow normal execution if it wasn't intercepted natively above
                        return query(args);
                    },
                },
            },
        });
    });
}
